spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@dbs-assignment03-bbags.mongodb.net/test?retryWrites=true&w=majority

  thymeleaf:
    cache: false

google:
  account: "jeewanthsdbs@jeewanthadbs.iam.gserviceaccount.com"
  filename: "assignment-trade.xlsx"